### ISSUE TITLE
Animixplay is missing

### ISSUE THREAD

**Issue by Kraaken132** [Carleslc/MyAnime#29]
can we please add animixplay it is a great site

**Comment by Carleslc** [comment]
I've updated the english providers, removing sites that were shut down and updating domains or adding new providers:

**ADDED**
- AniMixPlay
- Zoro

**REMOVED**
- 4Anime
- Aniwatch
- AnimeUltima
- MyAnimeCo

**DOMAIN UPDATE**
- AnimeFlix (io -> sbs)
- GogoAnime (movie -> cm & life -> nl)
- 9Anime (ru -> to)

I hope this works for you 🙂
Enjoy!

**Comment by Kraaken132** [comment]
thanks a lot

**Comment by Carleslc** [comment]
AniMixPlay is no longer active. Providers have been updated.

**ADDED**

- YugenAnime
- AnimeSuge
- animepahe

**REMOVED**

- AniMixPlay
- MasterAnime
- Twist

**DOMAIN UPDATE**

- GogoAnime (cm -> bid & nl -> page)
- Animeflix (sbs -> live)
- AnimeFenix (com -> tv)
